export const privacyInventory = {
  reviewedAt: "2026-08-11",
  website: {
    delivery: "Statisch exportierte HTML-, CSS-, JavaScript-, Schrift- und Bilddateien über HTTPS",
    hostingProvider: "ALL-INKL",
    serverData: [
      "IP-Adresse",
      "Zeitpunkt des Zugriffs",
      "angeforderte Datei",
      "Referrer, soweit übermittelt",
      "Browser- und Systeminformationen, soweit übermittelt",
    ],
    analytics: true,
    trackingPixels: false,
    marketingCookies: false,
  },
  browserStorage: {
    cookies: [
      "kfbh_analytics_consent: notwendige Speicherung der Analytics-Auswahl für 180 Tage",
      "_ga: optional nach Einwilligung, konfigurierte Laufzeit bis zu 180 Tage",
      "_ga_WD56RCXD03: optional nach Einwilligung, konfigurierte Laufzeit bis zu 180 Tage",
    ] as readonly string[],
    localStorage: [] as readonly string[],
    sessionStorage: [] as readonly string[],
    consentStorage: true,
    phpSession: false,
  },
  externalRuntimeResources: [
    "www.googletagmanager.com: Google-Tag erst nach Analytics-Einwilligung",
    "google-analytics.com und regionale Analytics-Endpunkte: Messdaten erst nach Analytics-Einwilligung",
  ] as readonly string[],
  analytics: {
    provider: "Google Analytics 4 / Google Ireland Limited",
    measurementId: "G-WD56RCXD03",
    loadingMode: "Basic Consent Mode; kein Google-Tag und keine Datenübertragung vor Einwilligung",
    measuredEvents: ["page_view", "generate_lead", "click_phone", "click_whatsapp", "click_google_review"],
    excludedFormData: ["Name", "Telefon", "E-Mail", "Abholadresse", "Zieladresse", "Fahrtanlass", "Hinweise"],
    advertisingConsent: false,
    googleSignals: false,
  },
  form: {
    endpoint: "/api/fahrtanfrage.php",
    fields: [
      "Vorname und Nachname",
      "Telefonnummer",
      "optionale E-Mail-Adresse",
      "Fahrtdatum",
      "Uhrzeit",
      "Abholadresse",
      "Zieladresse",
      "Fahrtart beziehungsweise Anlass",
      "Angabe zu Hin- und Rückfahrt",
      "zusätzliche Hinweise",
      "ausdrückliche Einwilligung zur Verarbeitung möglicherweise gesundheitsbezogener Angaben und zur Kontaktaufnahme",
      "technische Formularzeit",
    ],
    excludedData: ["Diagnosen", "Versicherungsnummern", "Dokument-Uploads", "medizinische Notfalldaten"],
    databaseStorage: false,
    recipient: "anfrage@krankenfahrten-bad-homburg.de",
    automaticUserConfirmation: false,
    rateLimit: {
      identifier: "HMAC-gehashte IP-Kennung; die vollständige IP-Adresse wird nicht in der Rate-Limit-Datei gespeichert",
      storage: "temporäre dateibasierte Speicherung außerhalb des öffentlichen Webroots",
      configuredWindowSeconds: 600,
      configuredMaximumRequests: 10,
      cleanupLimitation: "Veraltete Zeitstempel werden beim nächsten Zugriff auf dieselbe Kennung entfernt; Dateien werden nicht durch einen eigenen geplanten Bereinigungslauf gelöscht.",
    },
  },
  email: {
    recipient: "anfrage@krankenfahrten-bad-homburg.de",
    sender: "technische Adresse derselben Domain aus der serverseitigen PHP-Konfiguration",
    replyTo: "nur eine serverseitig validierte, optional angegebene Nutzeradresse",
    transport: "authentifizierter, TLS-verschlüsselter SMTP-Versand über die Hostinginfrastruktur",
    mailboxStorage: true,
    calendarAttachment: {
      format: "iCalendar-Datei mit den bereits für die Fahrtanfrage übermittelten Angaben",
      generation: "ausschließlich im Arbeitsspeicher des PHP-Prozesses",
      recipient: "ausschließlich das interne Anfragepostfach",
      persistentWebStorage: false,
      externalCalendarApi: false,
      import: "bewusst und manuell durch den internen Empfänger",
    },
  },
  openVerificationItems: [
    "Speicherdauer und genauer Umfang der Server-Logfiles bei ALL-INKL",
    "Vertrags- und Auftragsverarbeitungsdetails mit ALL-INKL",
    "betriebliche Löschfrist für Fahrtanfragen im E-Mail-Postfach",
    "branchenspezifische und anbieterrechtliche Pflichtangaben",
    "Google-Analytics-Kontoeinstellungen: Datenfreigabe, Google Signals und Aufbewahrungsdauer vor Live-Schaltung bestätigen",
    "Consent- und Netzwerkprüfung auf Test- und Produktionsdomain nach Deployment",
  ],
} as const;

export const consentBannerRequired = true;
