export const privacyInventory = {
  reviewedAt: "2026-07-21",
  website: {
    delivery: "Statisch exportierte HTML-, CSS-, JavaScript-, Schrift- und Bilddateien über HTTPS",
    hostingProvider: "ALL-INKL",
    serverData: [
      "IP-Adresse",
      "Zeitpunkt des Zugriffs",
      "angeforderte Datei",
      "Referrer, soweit übermittelt",
      "Browser- und Systeminformationen, soweit übermittelt",
    ],
    analytics: false,
    trackingPixels: false,
    marketingCookies: false,
  },
  browserStorage: {
    cookies: [] as readonly string[],
    localStorage: [] as readonly string[],
    sessionStorage: [] as readonly string[],
    consentStorage: false,
    phpSession: false,
  },
  externalRuntimeResources: [] as readonly string[],
  form: {
    endpoint: "/api/fahrtanfrage.php",
    fields: [
      "Vorname und Nachname",
      "Telefonnummer",
      "optionale E-Mail-Adresse",
      "Fahrtdatum",
      "Uhrzeit",
      "Abholadresse",
      "Zieladresse",
      "Fahrtart beziehungsweise Anlass",
      "Angabe zu Hin- und Rückfahrt",
      "zusätzliche Hinweise",
      "Einwilligung zur Kontaktaufnahme",
      "technische Formularzeit",
    ],
    excludedData: ["Diagnosen", "Versicherungsnummern", "Dokument-Uploads", "medizinische Notfalldaten"],
    databaseStorage: false,
    recipient: "anfrage@krankenfahrten-bad-homburg.de",
    automaticUserConfirmation: false,
    rateLimit: {
      identifier: "HMAC-gehashte IP-Kennung; die vollständige IP-Adresse wird nicht in der Rate-Limit-Datei gespeichert",
      storage: "temporäre dateibasierte Speicherung außerhalb des öffentlichen Webroots",
      configuredWindowSeconds: 600,
      configuredMaximumRequests: 10,
      cleanupLimitation: "Veraltete Zeitstempel werden beim nächsten Zugriff auf dieselbe Kennung entfernt; Dateien werden nicht durch einen eigenen geplanten Bereinigungslauf gelöscht.",
    },
  },
  email: {
    recipient: "anfrage@krankenfahrten-bad-homburg.de",
    sender: "technische Adresse derselben Domain aus der serverseitigen PHP-Konfiguration",
    replyTo: "nur eine serverseitig validierte, optional angegebene Nutzeradresse",
    transport: "PHP mail() über die Hostinginfrastruktur",
    mailboxStorage: true,
  },
  openVerificationItems: [
    "Speicherdauer und genauer Umfang der Server-Logfiles bei ALL-INKL",
    "Vertrags- und Auftragsverarbeitungsdetails mit ALL-INKL",
    "betriebliche Löschfrist für Fahrtanfragen im E-Mail-Postfach",
    "fachliche Zuordnung und Freigabe der Rechtsgrundlagen",
    "zuständige Datenschutzaufsichtsbehörde",
    "branchenspezifische und anbieterrechtliche Pflichtangaben",
  ],
} as const;

export const consentBannerRequired = false;
